import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/constants/app_assets.dart';
import '../models/tool_definition.dart';

/// MenuFragment's complete Android tool catalogue.
///
/// Kept in the view-model layer so another app skin can reuse the actions and
/// data while replacing only the page widgets.
final menuToolDefinitionsProvider = Provider<List<ToolDefinition>>((ref) {
  return const [
    ToolDefinition(
      id: ToolId.qrGenerate,
      title: '生成二维码',
      subtitle: '生成自定义专属二维码',
      iconAsset: AppAssets.menuFragmentQrGenerateBanner,
      favoriteIconAsset: AppAssets.favoriteQrGenerate,
      destination: ToolDestination.qrGenerate,
      placement: MenuToolPlacement.qrBanner,
    ),
    ToolDefinition(
      id: ToolId.textRecognition,
      title: '文字识别',
      iconAsset: AppAssets.menuFragmentQuickTextRecognition,
      favoriteIconAsset: AppAssets.favoriteTextRecognition,
      backgroundColor: Color(0xFFF6F485),
      destination: ToolDestination.recognitionText,
      placement: MenuToolPlacement.quickAction,
    ),
    ToolDefinition(
      id: ToolId.qrRecognition,
      title: '二维码识别',
      iconAsset: AppAssets.menuFragmentQuickQrRecognition,
      favoriteIconAsset: AppAssets.favoriteQrScan,
      backgroundColor: Color(0xFFD8D4F8),
      destination: ToolDestination.qrScan,
      placement: MenuToolPlacement.quickAction,
    ),
    ToolDefinition(
      id: ToolId.plantRecognition,
      title: '花草识别',
      iconAsset: AppAssets.menuFragmentQuickPlantRecognition,
      favoriteIconAsset: AppAssets.favoritePlantRecognition,
      backgroundColor: Color(0xFFC8E3E8),
      destination: ToolDestination.recognitionPlant,
      placement: MenuToolPlacement.quickAction,
    ),
    ToolDefinition(
      id: ToolId.ingredientRecognition,
      title: '果蔬识别',
      iconAsset: AppAssets.menuFragmentQuickIngredientRecognition,
      favoriteIconAsset: AppAssets.favoriteIngredientRecognition,
      backgroundColor: Color(0xFFD2D2FF),
      destination: ToolDestination.recognitionIngredient,
      placement: MenuToolPlacement.quickAction,
    ),
    ToolDefinition(
      id: ToolId.animalRecognition,
      title: '动物识别',
      iconAsset: AppAssets.menuFragmentQuickAnimalRecognition,
      favoriteIconAsset: AppAssets.favoriteAnimalRecognition,
      backgroundColor: Color(0xFFA4E1F1),
      destination: ToolDestination.recognitionAnimal,
      placement: MenuToolPlacement.quickAction,
    ),
    ToolDefinition(
      id: ToolId.watermark,
      title: '添加水印',
      subtitle: '专业水印保护',
      iconAsset: AppAssets.menuFragmentToolWatermark,
      favoriteIconAsset: AppAssets.favoriteWatermark,
      backgroundColor: Color(0xFFF0EDFD),
      destination: ToolDestination.watermark,
      placement: MenuToolPlacement.commonTool,
    ),
    ToolDefinition(
      id: ToolId.mosaic,
      title: '马赛克',
      subtitle: '保护隐私更安全',
      iconAsset: AppAssets.menuFragmentToolMosaic,
      favoriteIconAsset: AppAssets.favoriteMosaic,
      backgroundColor: Color(0xFFECF5F8),
      destination: ToolDestination.pixelImage,
      placement: MenuToolPlacement.commonTool,
    ),
    ToolDefinition(
      id: ToolId.magnifier,
      title: '放大镜',
      subtitle: '文字放大辅助工具',
      iconAsset: AppAssets.menuFragmentToolMagnifier,
      favoriteIconAsset: AppAssets.favoriteMagnifier,
      backgroundColor: Color(0xFFE5F8FC),
      destination: ToolDestination.magnifier,
      placement: MenuToolPlacement.commonTool,
    ),
    ToolDefinition(
      id: ToolId.spyglass,
      title: '望远镜',
      subtitle: '查看远景更方便',
      iconAsset: AppAssets.menuFragmentToolSpyglass,
      favoriteIconAsset: AppAssets.favoriteSpyglass,
      backgroundColor: Color(0xFFFCF4E5),
      destination: ToolDestination.spyglass,
      placement: MenuToolPlacement.commonTool,
    ),
    ToolDefinition(
      id: ToolId.pixelImage,
      title: '像素图',
      iconAsset: AppAssets.otherScanPixel,
      favoriteIconAsset: AppAssets.favoritePixel,
      backgroundColor: Color(0xFFFAC85C),
      destination: ToolDestination.pixelImage,
      placement: MenuToolPlacement.otherScanImageProcess,
    ),
    ToolDefinition(
      id: ToolId.lowPoly,
      title: '特效图',
      iconAsset: AppAssets.otherScanStyle,
      favoriteIconAsset: AppAssets.favoriteStyle,
      backgroundColor: Color(0xFFD2D2FF),
      destination: ToolDestination.lowPoly,
      placement: MenuToolPlacement.otherScanImageProcess,
    ),
    ToolDefinition(
      id: ToolId.hiddenImage,
      title: '隐藏图',
      iconAsset: AppAssets.otherScanHiddenImage,
      favoriteIconAsset: AppAssets.favoriteHiddenImage,
      backgroundColor: Color(0xFFACCFD6),
      destination: ToolDestination.hiddenImage,
      placement: MenuToolPlacement.otherScanImageProcess,
    ),
    ToolDefinition(
      id: ToolId.imageColourize,
      title: '黑白上色',
      iconAsset: AppAssets.otherScanColourize,
      favoriteIconAsset: AppAssets.favoriteColourize,
      backgroundColor: Color(0xFFA4E1F1),
      destination: ToolDestination.imageColourize,
      placement: MenuToolPlacement.otherScanImageProcess,
    ),
    ToolDefinition(
      id: ToolId.relativesCalculator,
      title: '亲戚关系\n计算器',
      iconAsset: AppAssets.otherScanRelatives,
      favoriteIconAsset: AppAssets.favoriteRelatives,
      backgroundColor: Color(0xFFFAC85C),
      destination: ToolDestination.relativesCalculator,
      placement: MenuToolPlacement.otherScanCalculator,
    ),
    ToolDefinition(
      id: ToolId.currencyConverter,
      title: '汇率换算',
      iconAsset: AppAssets.otherScanCurrency,
      favoriteIconAsset: AppAssets.favoriteCurrency,
      backgroundColor: Color(0xFFD2D2FF),
      destination: ToolDestination.currencyConverter,
      placement: MenuToolPlacement.otherScanCalculator,
    ),
    ToolDefinition(
      id: ToolId.dateCalculator,
      title: '日期计算器',
      iconAsset: AppAssets.otherScanDate,
      favoriteIconAsset: AppAssets.favoriteDate,
      backgroundColor: Color(0xFFA4E1F1),
      destination: ToolDestination.dateCalculator,
      placement: MenuToolPlacement.otherScanCalculator,
    ),
    ToolDefinition(
      id: ToolId.baseConverter,
      title: '进制转换器',
      iconAsset: AppAssets.otherScanBase,
      favoriteIconAsset: AppAssets.favoriteBase,
      backgroundColor: Color(0xFFACCFD6),
      destination: ToolDestination.baseConverter,
      placement: MenuToolPlacement.otherScanCalculator,
    ),
    ToolDefinition(
      id: ToolId.jsonEditor,
      title: 'json编辑器',
      iconAsset: AppAssets.otherScanJsonEditor,
      favoriteIconAsset: AppAssets.otherScanJsonEditor,
      backgroundColor: Color(0xFFD2D2FF),
      destination: ToolDestination.jsonEditor,
      placement: MenuToolPlacement.otherScanOther,
    ),
    ToolDefinition(
      id: ToolId.randomNumber,
      title: '随机数生成',
      iconAsset: AppAssets.otherScanRandom,
      favoriteIconAsset: AppAssets.favoriteRandom,
      backgroundColor: Color(0xFFFAC85C),
      destination: ToolDestination.randomNumber,
      placement: MenuToolPlacement.otherScanOther,
    ),
    // PDF 工具分类(对齐 OtherSaoMiaoFrgment 的 "PDF工具" 分组与顺序)。
    ToolDefinition(
      id: ToolId.pdfToImage,
      title: 'PDF转图片',
      iconAsset: AppAssets.otherScanPdfToImage,
      favoriteIconAsset: AppAssets.otherScanPdfToImage,
      backgroundColor: Color(0xFFACCFD6),
      destination: ToolDestination.pdfToImage,
      placement: MenuToolPlacement.otherScanPdf,
    ),
    ToolDefinition(
      id: ToolId.imageToPdf,
      title: '图片转PDF',
      iconAsset: AppAssets.otherScanImageToPdf,
      favoriteIconAsset: AppAssets.otherScanImageToPdf,
      backgroundColor: Color(0xFFFAC85C),
      destination: ToolDestination.imageToPdf,
      placement: MenuToolPlacement.otherScanPdf,
    ),
    ToolDefinition(
      id: ToolId.pdfCompress,
      title: '压缩PDF',
      iconAsset: AppAssets.otherScanPdfCompress,
      favoriteIconAsset: AppAssets.otherScanPdfCompress,
      backgroundColor: Color(0xFFA4E1F1),
      destination: ToolDestination.pdfCompress,
      placement: MenuToolPlacement.otherScanPdf,
    ),
    ToolDefinition(
      id: ToolId.pdfEncrypt,
      title: '加密PDF',
      iconAsset: AppAssets.otherScanPdfEncrypt,
      favoriteIconAsset: AppAssets.otherScanPdfEncrypt,
      backgroundColor: Color(0xFFD2D2FF),
      destination: ToolDestination.pdfEncrypt,
      placement: MenuToolPlacement.otherScanPdf,
    ),
    ToolDefinition(
      id: ToolId.eatToday,
      title: '今天吃什么',
      iconAsset: AppAssets.otherScanEat,
      favoriteIconAsset: AppAssets.favoriteEat,
      backgroundColor: Color(0xFFACCFD6),
      destination: ToolDestination.eatToday,
      placement: MenuToolPlacement.otherScanOther,
    ),
    // ToolDefinition(
    //   id: ToolId.notebook,
    //   title: '记事本',
    //   iconAsset: AppAssets.otherScanNotebook,
    //   favoriteIconAsset: AppAssets.otherScanNotebook,
    //   backgroundColor: Color(0xFFA4E1F1),
    //   destination: ToolDestination.notebook,
    //   placement: MenuToolPlacement.otherScanOther,
    // ),
    // ToolDefinition(
    //   id: ToolId.travelChecklist,
    //   title: '旅行清单',
    //   iconAsset: AppAssets.otherScanChecklist,
    //   favoriteIconAsset: AppAssets.otherScanChecklist,
    //   backgroundColor: Color(0xFFD2D2FF),
    //   destination: ToolDestination.travelChecklist,
    //   placement: MenuToolPlacement.otherScanOther,
    // ),
  ];
});
